sudo: false
language: ruby
cache: bundler
bundler_args: --deployment
rvm:
  - 2.1.10
  - 2.2.10
  - 2.3.7
  - 2.4.4
  - 2.5.1
script:
  - 'bundle exec ruby irc_map config'
  - 'bundle exec ruby irc_map'
  - 'bundle exec ruby irc_channels config'
  - 'bundle exec ruby irc_channels'
  - 'bundle exec ruby irc_clients config'
  - 'bundle exec ruby irc_clients'
notifications:
  irc:
    use_notice: true
    channels: 
      - 'irc.trpg.net#koi-chan'
    on_success: always
    on_failure: always
    template:
      - '%{repository_slug} #%{build_number} %{branch} - %{commit} -> %{result}'
      - '変更履歴: %{compare_url}'
      - 'ステータス: %{build_url}'
  email: false
