#!/usr/bin/ruby

#Dir.chdir(File.dirname(__FILE__))
Dir.chdir('/home/server-admin/git/gitlab/munin-irc/ruby')

require 'bundler/setup'
require 'irc-socket'

if ARGV[0] == 'config'
  puts <<__EOT__
graph_category irc
graph_title ircd channels
graph_order channels
graph_args -l 0
channels.label channels
channels.draw LINE2
__EOT__
  exit
end

irc = IRCSocket.new('localhost')
irc.connect

if irc.connected?
  irc.nick('munin-node')
  irc.user('munin-node', 0, '*', 'munin-node')

  while line = irc.read.split
    if line[1] == '254'
      puts "channels.value #{line[3]}"
      break
    end
  end
end

irc.close
