#!/usr/bin/ruby

# 自分自身がシンボリックリンクだった場合、本体の格納先に移動する
# ライブラリなどを読み込むために必要
if File.ftype(__FILE__) === 'link'
  Dir.chdir(File.dirname(File.readlink(__FILE__)))
end

require 'bundler/setup'
require 'irc-socket'

require_relative 'config'


# munin プラグインとしての処理
# 設定出力を指定された場合、設定値を出力して終了する
if ARGV[0] == 'config'
  puts <<__EOT__
graph_category irc
graph_title ircd global clients
graph_order clients
graph_args -l 0
clients.label clients
clients.draw LINE2
__EOT__
  exit
end


# プラグインとしての本体の処理
irc = IRCSocket.new(TARGET)
irc.connect

if irc.connected?
  irc.nick('munin-node')
  irc.user('munin-node', 0, '*', 'munin-node')

  while line = irc.read.split
    if line[1] == '266'
      puts "clients.value #{line[3]}"
      break
    end
  end
end

irc.close
